In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/weekly_ae_activity_20240114.csv')
df.head(15)

,WeekEndingDate,Country,HBT,TreatmentLocation,DepartmentType,NumberOfAttendancesEpisode,NumberWithin4HoursEpisode,NumberOver4HoursEpisode,PercentageWithin4HoursEpisode,NumberOver8HoursEpisode,PercentageOver8HoursEpisode,NumberOver12HoursEpisode,PercentageOver12HoursEpisode
0,20150222,S92000003,S08000015,A210H,Emergency Department,814,624,190,76.7,21,2.6,2,0.2
1,20150222,S92000003,S08000015,A111H,Emergency Department,1347,1115,232,82.8,31,2.3,2,0.1
2,20150222,S92000003,S08000016,B120H,Emergency Department,517,463,54,89.6,1,0.2,0,0.0
3,20150222,S92000003,S08000017,Y146H,Emergency Department,604,578,26,95.7,0,0.0,0,0.0
4,20150222,S92000003,S08000017,Y144H,Emergency Department,196,185,11,94.4,1,0.5,0,0.0
5,20150222,S92000003,S08000029,F704H,Emergency Department,1284,1135,149,88.4,22,1.7,7,0.5
6,20150222,S92000003,S08000019,V217H,Emergency Department,1095,1053,42,96.2,0,0.0,0,0.0
7,20150222,S92000003,S08000020,N101H,Emergency Department,1116,952,164,85.3,36,3.2,3,0.3
8,20150222,S92000003,S08000020,N411H,Emergency Department,434,409,25,94.2,2,0.5,1,0.2
9,20150222,S92000003,S08000020,N121H,Emergency Department,327,320,7,97.9,0,0.0,0,0.0
10,20150222,S92000003,S08000031,G107H,Emergency Department,1550,1173,377,75.7,55,3.5,1,0.1
11,20150222,S92000003,S08000031,C313H,Emergency Department,625,523,102,83.7,7,1.1,0,0.0
12,20150222,S92000003,S08000031,C418H,Emergency Department,1296,971,325,74.9,67,5.2,18,1.4
13,20150222,S92000003,S08000031,G513H,Emergency Department,961,950,11,98.9,0,0.0,0,0.0
14,20150222,S92000003,S08000031,G405H,Emergency Department,928,678,250,73.1,53,5.7,12,1.3

In [3]:
df.shape

(13979, 13)

In [8]:
df.dtypes

WeekEndingDate                     int64
Country                           object
HBT                               object
TreatmentLocation                 object
DepartmentType                    object
NumberOfAttendancesEpisode         int64
NumberWithin4HoursEpisode          int64
NumberOver4HoursEpisode            int64
PercentageWithin4HoursEpisode    float64
NumberOver8HoursEpisode            int64
PercentageOver8HoursEpisode      float64
NumberOver12HoursEpisode           int64
PercentageOver12HoursEpisode     float64
dtype: object

In [4]:
trusts = pd.read_csv('data/hb14_hb19.csv')
trusts.head()

,HB,HBName,HBDateEnacted,HBDateArchived,Country
0,S08000015,NHS Ayrshire and Arran,20140401,NaN,S92000003
1,S08000016,NHS Borders,20140401,NaN,S92000003
2,S08000017,NHS Dumfries and Galloway,20140401,NaN,S92000003
3,S08000018,NHS Fife,20140401,20180201.0,S92000003
4,S08000019,NHS Forth Valley,20140401,NaN,S92000003

In [5]:
hospitals = pd.read_csv('data/hospitals.csv')
hospitals.head()

,HospitalCode,HospitalName,AddressLine1,AddressLine2,AddressLine2QF,AddressLine3,AddressLine3QF,AddressLine4,AddressLine4QF,Postcode,HealthBoard,HSCP,CouncilArea,IntermediateZone,DataZone
0,A101H,Arran War Memorial Hospital,Lamlash,Isle of Arran,NaN,NaN,z,NaN,z,KA278LF,S08000015,S37000020,S12000021,S02002097,S01011176
1,A103H,Ayrshire Central Hospital,Kilwinning Road,Irvine,NaN,NaN,z,NaN,z,KA128SS,S08000015,S37000020,S12000021,S02002105,S01011213
2,A105H,Kirklandside Hospital,Kirklandside,Kilmarnock,NaN,Ayrshire,NaN,NaN,z,KA1 5LH,S08000015,S37000008,S12000008,S02001492,S01007961
3,A110H,Lady Margaret Hospital,College St,Millport,NaN,Isle of Cumbrae,NaN,NaN,z,KA280HF,S08000015,S37000020,S12000021,S02002128,S01011328
4,A111H,University Hospital Crosshouse,Kilmarnock Road,Kilmarnock,NaN,Ayrshire,NaN,NaN,z,KA2 0BE,S08000015,S37000008,S12000008,S02001504,S01008027

In [6]:
hospitals.shape

(276, 15)